server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  error:
    include-message: always

polar:
  greeting: Welcome to the local Book Catalog!